// src/components/EditForm.vue
<script setup lang="ts">
import JournalEntry from "@/service/journalEntry";
import SimpleModal from "./SimpleModal.vue";
import { computed, ref, watch } from "vue";
import DayTypeLib, { DayType } from "@/service/dayType";
import { Context } from "@/service/appContext";
import DateLib from "@/service/dateHelpers";

const props = defineProps<{
  entry: JournalEntry | undefined
}>();

const emits = defineEmits<{
  "closed": [void]
}>();

watch(() => props.entry, async (newQ) => {
  if (newQ) {
    editing.value = true;
    setTo(newQ);
  }
});

function setTo(entry?: JournalEntry) {
  amount.value = entry?.amount ?? 0;
  isIncome.value = entry?.isIncome ?? false;
  category.value = entry?.category ?? '';
  startDate.value = (entry?.from ?? DateLib.addOffsetToDate(new Date())).toISOString().substring(0, 10);
  periodCount.value = entry?.lengthCount ?? 1;
  periodType.value = entry?.lengthType ?? DayType.Day;
  repeats.value = entry?.repeats ?? false;
  lastDay.value = entry?.lastDay ? entry.lastDay.toISOString().substring(0, 10) : '';
  note.value = entry?.note || '';
  deleteConfirm.value = false;
  formAlert.value = '';
}

const editing = ref(false);
const formAlert = ref("");

const amount = ref(0);
const isIncome = ref(false);
const category = ref("");
const startDate = ref(DateLib.addOffsetToDate(new Date()).toISOString().substring(0, 10));
const periodCount = ref(1);
const periodType = ref(DayType.Day);
const repeats = ref(false);
const lastDay = ref("");
const note = ref("");

const deleteConfirm = ref(false);

const perDay = computed(() => {
  if (amount.value && periodType.value && periodCount.value) {
    return amount.value/DayTypeLib.calcDayCount(periodType.value, periodCount.value);
  }
  return 0;
});

const categories = computed(() => Context.value.calc.categories);

function selectItemEventHandler(item: any) {
  category.value = item;
}
function onBlurEventHandler(event: any) {
  category.value = event.input.value;
}

function handleModalCancel() {
  setTo(undefined);
  emits('closed');
  editing.value = false;
}

function handleModalConfirm() {
  if (!amount.value) { formAlert.value = "Please set a total amount"; return; }
  if (!category.value) { formAlert.value = "Please set a category"; return; }
  if (!startDate.value) { formAlert.value = "Please set a start date"; return; }
  if (!(periodCount.value) || !(periodType.value)) {
    formAlert.value = "Select both period length and period type";
    return;
  }

  const startDateDate = new Date(Date.parse(startDate.value));

  const entry = new JournalEntry(startDateDate, amount.value, periodCount.value, periodType.value, category.value.toLocaleLowerCase());
  entry.id = props.entry && props.entry instanceof JournalEntry ? props.entry.id : -1;
  entry.isIncome = isIncome.value;
  entry.repeats = repeats.value;
  if (lastDay.value)
    entry.lastDay = new Date(Date.parse(lastDay.value));
  
  const message = entry.validate();
  if (message) {
    formAlert.value = message;
    return;
  }

  console.log("Saving:", entry);
  Context.value.saveRow(entry, () => {
    // set everything back to the default
    setTo(undefined);
    emits('closed');
    editing.value = false;
  }, (str) => {
    formAlert.value = str;
  });
}

const headingTextBetter = computed(() => props.entry ? "Edit Record" : "Add Record" + ": $"+ Math.round(perDay.value * 100)/100 + "/day");

function deleteEntry() {
  if (!props.entry) {
    alert("Deleting an entry that doesn't exist");
    setTo(undefined);
    emits('closed');
    editing.value = false;
    return;
  }

  Context.value.deleteRow(props.entry, () => {
    // set everything back to the default
    setTo(undefined);
    emits('closed');
    editing.value = false;
  }, (str) => {
    formAlert.value = str;
  });
}
</script>

<template>
  
  <span class="float-start">
    <button class="btn btn-primary" :disabled="editing" @click="editing = true">Add</button>
  </span>

  <SimpleModal :open="editing" :heading-text="headingTextBetter" cancel-text="Cancel" confirm-text="Save Changes" @cancelled="handleModalCancel" @confirm="handleModalConfirm">
    <p v-if="formAlert" class="error">{{ formAlert }}</p>
    <form class="form-inline">
      <div class="row mb-2">
        <div class="col-7">
          <label for="amount" class="form-label">Amount</label>
          <div class="input-group">
            <span class="input-group-text">$</span>
            <input type="number" id="amount" class="form-control" v-model="amount" :autofocus="!props.entry" />
          </div>
        </div>
        <div class="col-5 form-check">
          <input type="checkbox" class="form-check-input" :checked="isIncome" id="isIncome" />
          <label for="isIncome" class="form-check-label">Is Income</label>
        </div>
      </div>
      <div class="row mb-2">
        <label for="category" class="col-4 col-form-label">Category</label>
        <div class="col-8">
          <vue3-simple-typeahead class="form-control"
            id="category"
            :items="categories"
            :minInputLength="0"
            :defaultItem="category"
            @selectItem="selectItemEventHandler"
            @onBlur="onBlurEventHandler"
            >
            <template #list-item-text="slot"><span v-html="slot.boldMatchText(slot.itemProjection(slot.item))"></span></template>
          </vue3-simple-typeahead>
        </div>
      </div>
      <div class="row mb-2">
        <label for="startDate" class="col-form-label col-4">Start Date</label>
        <div class="col-8">
          <input type="date" class="form-control" id="startDate" v-model="startDate" />
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-4">
          <input type="number" class="form-control" v-model="periodCount" />
        </div>
        <div class="col-8">
          <select class="form-select" v-model="periodType">
            <option :value="DayType.Day">Day</option>
            <option :value="DayType.Week">Week</option>
            <option :value="DayType.Month">Month</option>
            <option :value="DayType.Quarter">Quarter</option>
            <option :value="DayType.Year">Year</option>
          </select>
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-4 form-check">
          <input type="checkbox" class="form-check-input" id="repeats" :checked="repeats" />
          <label for="repeats" class="form-check-label">Repeats</label>
        </div>
        <div class="col-8">
          <input type="date" class="form-control" v-model="lastDay" />
        </div>
      </div>
      <div class="row mb-2">
        <div class="col-4">
          <label class="form-label col-xs-4">Free Text</label>
        </div>
        <div class="col-8">
          <textarea class="form-control" v-model="note" rows="3"></textarea>
        </div>
      </div>
    </form>
    <div class="row">
      <button v-if="props.entry" class="btn btn-danger col-3" @click="deleteConfirm = true" :disabled="deleteConfirm">Delete</button>
      <div class="col-3"></div>
      <button v-if="props.entry && deleteConfirm" class="btn btn-danger col-3" @click="deleteEntry" :disabled="!deleteConfirm">REALLY Delete</button>
    </div>
  </SimpleModal>
</template>

<style scoped>
.error {
  color: red;
}
</style>

// src/screen/edit-form.tsx
import React from "react";
import Alert from 'react-bootstrap/Alert';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
import Form from 'react-bootstrap/Form';
import FloatingLabel from "react-bootstrap/FloatingLabel";
import InputGroup from 'react-bootstrap/InputGroup';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import JournalEntry from "../utils/db-row";
import DayTypeLib, { DayType } from "../utils/day-type";
import TypeAhead from "../components/typeahead.js";
import DateLib from "../utils/date-helpers";
import Calc from "../utils/calc";

class EditFormProps {
    show: boolean;
    save: (row: JournalEntry) => void;
    exit: () => void;
    delete: (row: JournalEntry) => void;
    entry: JournalEntry;
    categoryList: Array<string>;
    calc: Calc;
}

const EditForm = (props: EditFormProps) => {
    const [alert, setAlert] = React.useState<string>();
    const getValueOf = (field: string, fallback: any): any => {
        if (props.entry) {
            return props.entry[field];
        }
        return fallback;
    }

    const amount = React.createRef<HTMLInputElement>();
    const isIncome = React.createRef<HTMLInputElement>();

    const fromDefault = DateLib.addOffsetToDate(new Date());
    const from = React.createRef<HTMLInputElement>();
    const periodCount = React.createRef<HTMLInputElement>();

    const periodType = React.createRef<HTMLSelectElement>();

    const repeats = React.createRef<HTMLInputElement>();
    const lastDay = React.createRef<HTMLInputElement>();
    
    const [category, setCategorySelections] = React.useState<Array<{label: string}>>([]);
    const [categorySearch, setCategorySearch] = React.useState(getValueOf('category', null));
    const categoryOnChange = (e: Array<{label:string}>) => {
        setCategorySelections(e);
        if (e && e.length > 0) {
            e[0].label = e[0].label.toLowerCase().trim();
            if (!props.entry) {
                var defaults = props.calc.getCategoryDefault(e[0].label);
                periodType.current.value = defaults.type.toString();
                periodCount.current.value = defaults.count.toString();
                
                //hide android keyboard
                if (document.activeElement instanceof HTMLElement) {
                    document.activeElement.blur();
                }
            }
        }
    }

    const note = React.createRef<HTMLTextAreaElement>();

    const [deleteConfirm, setDeleteConfirm] = React.useState(false);

    const save = (event: any) => {
        event.preventDefault();

        let categoryNew = category.length < 1 ? categorySearch : category[0];
        if (categoryNew && categoryNew.hasOwnProperty('label'))
            categoryNew = categoryNew.label;
        if (!categoryNew) {
            setAlert("Please set a category");
            return;
        }

        const entry = new JournalEntry();
        entry.id = props.entry ? props.entry.id : -1;
        entry.isIncome = isIncome.current.checked;
        entry.from = from.current.valueAsDate;
        entry.amount = amount.current.valueAsNumber;
        entry.lengthCount = periodCount.current.valueAsNumber;
        entry.lengthType = DayTypeLib.parseDayType(periodType.current.value);
        entry.repeats = repeats.current.checked;
        entry.lastDay = lastDay.current ? lastDay.current.valueAsDate : null;
        entry.category = categoryNew;
        entry.note = note.current.value;

        const message = entry.validate();
        if (message) {
            setAlert(message);
            return;
        }

        console.log("Saving:", entry);
        props.save(entry);
    }

    const [perDay, setPerDay] = React.useState(props.entry ? props.entry.calcPerDay() : 0);

    const setUpdatedPerDay = () => {
        let perDay = 0;
        if (amount.current && periodType.current && periodCount.current) {
            const dayType = DayTypeLib.parseDayType(periodType.current.value);
            perDay = amount.current.valueAsNumber/DayTypeLib.calcDayCount(dayType, +periodCount.current.valueAsNumber);
        }
        setPerDay(perDay);
    }
    
    return (
    <Modal show={props.show} onHide={props.exit} animation={false}>
        <Modal.Header closeButton>
            <Modal.Title>Add Record</Modal.Title>
        </Modal.Header>
        <Modal.Body>
            {alert ? <Alert variant="danger">{alert}</Alert> : null}
            <Form onSubmit={save}>
                <Form.Group as={Row} className="mb-3">
                    <Col xs={7}>
                        <InputGroup>
                            <InputGroup.Text>$</InputGroup.Text>
                            <FloatingLabel label="Amount">
                                <Form.Control type="number" defaultValue={getValueOf('amount', 0)} ref={amount} onChange={setUpdatedPerDay} autoFocus={!props.entry} />
                            </FloatingLabel>
                        </InputGroup>
                    </Col>
                    <Col xs={5}>
                        <Form.Check id="isIncome" ref={isIncome} label="Is Income" defaultChecked={getValueOf('isIncome', false)} />
                        ${perDay.toFixed(2)}/day
                    </Col>
                </Form.Group>

                <Form.Group as={Row} className="mb-3">
                    <Form.Label column xs={4}>Category</Form.Label>
                    <Col xs={8}>
                        <TypeAhead id="categoryButBetter"
                            options={props.categoryList.map(x => { return {'label':x};}) || []}
                            defaultSelected={[getValueOf('category', '')]}
                            onChange={categoryOnChange}
                            onInputChange={setCategorySearch}
                            placeholder="Select a Category"/>
                    </Col>
                </Form.Group>

                <Form.Group as={Row} className="mb-3">
                    <Form.Label column xs={4}>Start Date</Form.Label>
                    <Col xs={8}>
                        <Form.Control type="date" ref={from} defaultValue={getValueOf('from', fromDefault).toISOString().slice(0, 10)} />
                    </Col>
                </Form.Group>

                <Form.Group as={Row} className="mb-3">
                    <Col xs={4}>
                        <Form.Control type="number" min="0" ref={periodCount} defaultValue={getValueOf('lengthCount', 1)} onChange={setUpdatedPerDay}/>
                    </Col>
                    <Col xs={8}>
                        <Form.Select ref={periodType} defaultValue={getValueOf('lengthType', DayType.Day)} onChange={setUpdatedPerDay}>
                            <option value={DayType.Day}>Day</option>
                            <option value={DayType.Week}>Week</option>
                            <option value={DayType.Month}>Month</option>
                            <option value={DayType.Quarter}>Quarter</option>
                            <option value={DayType.Year}>Year</option>
                        </Form.Select>
                    </Col>
                </Form.Group>
                
                <Form.Group as={Row} className="mb-3">
                    <Col xs={4}>
                        <Form.Check id="repeats" ref={repeats} defaultChecked={getValueOf('repeats', false)} label="Repeats?" />
                    </Col>
                    <Col xs={8}>
                        <Form.Control type="date" ref={lastDay} defaultValue={getValueOf('lastDay', null) ? getValueOf('lastDay', null).toISOString().slice(0, 10) : null} />
                    </Col>
                </Form.Group>
                                
                <Form.Group as={Row} className="mb-3">
                    <Form.Label column xs={4}>Free text</Form.Label>
                    <Col xs={8}>
                        <Form.Control ref={note} as="textarea" defaultValue={getValueOf('note', null)} />
                    </Col>
                </Form.Group>
            </Form>
        </Modal.Body>
        <Modal.Footer>
            {props.entry && deleteConfirm && <Button variant="danger" onClick={() => props.delete(props.entry)}>REALLY DELETE?</Button>}
            <Button variant="secondary" onClick={props.exit}>Close</Button>
            <Button variant="primary" onClick={save}>Save Changes</Button>
            {props.entry && <Button variant="danger" disabled={deleteConfirm} onClick={() => setDeleteConfirm(true)}>Delete</Button>}
        </Modal.Footer>
    </Modal>
    );
};
export default EditForm;
