// src/components/report-raw.tsx
import JournalEntry from "../utils/db-row";

import React from "react";
import Table from 'react-bootstrap/Table';
import { DayType } from "../utils/day-type";

class ReportRawProps {
    data: JournalEntry[];
}

const ReportRaw = (props: ReportRawProps) => {
    return (<>
        <Table striped bordered hover size="sm">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>$/day</th>
                    <th>From</th>
                    <th>Math</th>
                    <th>Note</th>
                </tr>
            </thead>
            <tbody>
                {props.data
                    .sort((x, y) => x.calcPerDay() - y.calcPerDay())
                    .map(x =>
                        <tr>
                            <td>{x.category}</td>
                            <td>{((x.isIncome ? 1 : -1)*x.calcPerDay()).toFixed(2)}</td>
                            <td>{x.from.toLocaleDateString()}</td>
                            <td>${x.amount} @ {x.lengthCount + " * " + DayType[x.lengthType]} {x.repeats ? <code>forever</code> : ""}</td>
                            {getOptionalString(x.note)}
                        </tr>
                    )}
            </tbody>
        </Table>
    </>);
};

function getOptionalString(str: string | undefined) {
    if (str)
        return <td>{str}</td>;
    return <td></td>;
}

export default ReportRaw;

// src/components/report/ReportRaw.vue
<script setup lang="ts">
import { computed } from 'vue';
import type JournalEntry from '@/service/journalEntry';
import { DayType } from '../../service/dayType';

const props = defineProps<{
  data: JournalEntry[]
}>();

const dataSorted = computed(() => {
  return [...props.data].sort((x, y) => x.calcPerDay() - y.calcPerDay());
});
</script>

<template>
  <table class="table table-striped table-bordered table-hover table-sm">
    <thead>
      <tr>
        <th>Category</th>
        <th>$/day</th>
        <th>From</th>
        <th>Math</th>
        <th>Note</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="x in dataSorted" :key="x.category">
        <td>{{ x.category }}</td>
        <td style="text-align: end;">{{ x.calcPerDay().toFixed(2) }}</td>
        <td>{{ x.from.toLocaleDateString() }}</td>
        <td>${{ x.amount }} @ {{ x.lengthCount + " * " + DayType[x.lengthType] }} <code v-if="x.repeats">forever</code></td>
        <td>{{ x.note }}</td>
      </tr>
    </tbody>
  </table>
</template>
