// src/components/FullRecordList.vue
<script setup lang="ts">
import type JournalEntry from '@/service/journalEntry';
import SimpleModal from "./SimpleModal.vue";
import { computed, ref } from 'vue';
import { Context } from '@/service/appContext';
import { DayType } from '../service/dayType';
import DateLib from '@/service/dateHelpers';

const emit = defineEmits<{
  edit: [entry: JournalEntry]
}>();

const viewing = ref(false);
const filter = ref("");

const totalRecords = computed(() => {
  return Context.value.getRawData();
});

const recordsThisWeek = computed(() => totalRecords.value.filter(x => x.from > DateLib.addDays(new Date(), -7)));
const recordsToday = computed(() => totalRecords.value.filter(x => x.from > DateLib.addDays(new Date(), -1)));

const filteredData = computed(() => {
  const searchExp =  new RegExp(filter.value, "i");
  return totalRecords.value
    .filter(x => searchExp.test(x.category) || (x.note && searchExp.test(x.note)))
    .sort((x: JournalEntry, y: JournalEntry) => {
        return +y.from - +x.from;
    });
});

function editRow(row: JournalEntry) {
  viewing.value = false;
  emit('edit', row);
}

</script>

<template>
  <span class="float-end">
    <button class="btn btn-primary" :disabled="viewing" @click="viewing = true">View All</button>
  </span>

  <SimpleModal :open="viewing" heading-text="All Record Search" :show-footer="false">
    <button class="btn btn-primary float-end" @click="viewing = false">Close</button>
    <div class="row">
      <div class="col">
        <input type="text" v-model="filter" class="form-control" placeholder="Filter below" />
      </div>
      <div class="col">
        {{ filter }}
        Record count: {{ filteredData.length }} (total count: {{ totalRecords.length }})<br/>
        today: {{ recordsToday.length }}, week: {{ recordsThisWeek.length }}
      </div>
    </div>
    <table class="table table-sm table-hover table-bordered table-striped">
      <thead>
        <tr>
          <th>Category</th><th>Amount</th><th>Start Date</th><th>Length</th><th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="row in filteredData" :key="row.id">
          <td>{{ row.category }}</td>
          <td>${{ row.amount.toFixed(2) }}</td>
          <td>{{ row.from.toLocaleDateString() }}</td>
          <td>{{ row.repeats && !row.lastDay ? 'inf' : `${row.lengthCount} * ${DayType[row.lengthType]}` }}</td>
          <td><button class="btn btn-secondary" @click="editRow(row)">Edit</button></td>
        </tr>
      </tbody>
    </table>
  </SimpleModal>
</template>

// src/components/full-record-list.tsx
import * as React from "react";
import Pagination from 'react-bootstrap/Pagination';
import Table from 'react-bootstrap/Table';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';
import Container from 'react-bootstrap/Container';

import JournalEntry from "../utils/db-row";
import { DayType } from "../utils/day-type";
import DateUtil from "../utils/date-helpers";

const pageSize: number = 15;

type RecordListProps = {
    data: Array<JournalEntry>;
    edit: (row: JournalEntry) => void;
}

type EntryProps = {
    row: JournalEntry;
    edit: (row: JournalEntry) => void;
}

const Entry = (props: EntryProps) => {
    const perDay = (props.row.lengthType != DayType.Day || props.row.lengthCount != 1) ? ` ($${props.row.calcPerDay().toFixed(2)}/day)` : null;
    const length = props.row.repeats && !props.row.lastDay ? 'inf' : `${props.row.lengthCount} * ${DayType[props.row.lengthType]}`;
    return <tr key={props.row.id}>
        <td>{props.row.category}</td>
        <td>${props.row.amount.toFixed(2)}{perDay}</td>
        <td>{props.row.from.toLocaleDateString()}</td>
        <td>{length}</td>
        <td><Button onClick={() => props.edit(props.row)}>Edit</Button></td>
    </tr>;
}

const FullRecordList = (props: RecordListProps) => {
    const [pageNum, setPageNum] = React.useState(0);
    const [filter, setFilter] = React.useState("");

    const data = props.data.filter(x => x.category.includes(filter)).sort((x: JournalEntry, y: JournalEntry) => {
        return +y.from - +x.from;
    });

    const pages = data.length/pageSize;
    const paginationItems = [];
    for (let i = 0; i < pages && i < 5; i++)
        paginationItems.push(<Pagination.Item key={i} active={i === pageNum} onClick={() => setPageNum(i)}>
            {i+1}
          </Pagination.Item>);
    if (pages > 5)
        paginationItems.push(<Pagination.Ellipsis />);

    const items = [];
    for (let i = pageSize*pageNum; i < data.length && i < pageSize*(pageNum+1); i++) {
        items.push(<Entry row={data[i]} key={i+"page"} edit={props.edit}/>);
    }

    const recordsToday = props.data.filter(x => x.from > DateUtil.addDays(new Date(), -1));
    const recordsThisWeek = props.data.filter(x => x.from > DateUtil.addDays(new Date(), -7));

    return <>
        <Container>
            <Row>
                <Col>
                    <Form.Control value={filter} onChange={(e) => setFilter(e.currentTarget.value)} placeholder="Filter below"/>
                </Col>
                <Col>
                    Record count: {data.length} (total count: {props.data.length})<br/>
                    today: {recordsToday.length}, week: {recordsThisWeek.length}
                </Col>
            </Row>
        </Container>
        
        <Table striped bordered hover size="sm">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Amount</th>
                    <th>Date</th>
                    <th>Length</th>
                </tr>
            </thead>
            <tbody>
                {items}
            </tbody>
        </Table>
        
        <Pagination>{paginationItems}</Pagination>
    </>;
}

export default FullRecordList;
