// src/components/records-today.tsx
import React from "react";

import Calc from "../utils/calc";
import DateLib from "../utils/date-helpers";
import DayTypeLib, { DayType } from "../utils/day-type";

class RecordsTodayProps {
    calc: Calc;
}

const RecordsToday = (props: RecordsTodayProps) => {

    const today = DateLib.treatAsUTC(DayTypeLib.setToStart(new Date(), DayType.Day));
    const recordsToday = props.calc.rowsForDay(today).filter(x => x.from.getTime() === today.getTime());

    if (!recordsToday || recordsToday.length < 1) {
        return <></>;
    }

    const formattedRecords = recordsToday.map(x =>
        <div>
            - {x.category} <code>${x.amount.toFixed(2)}</code> for <code>${Math.abs(x.calcPerDay()).toFixed(2)}</code>/d
        </div>
        );

    return <>
        <p>Records that start today:<br /> {formattedRecords}</p>
    </>
}


export default RecordsToday;

// src/components/RecordsToday.vue
<script setup lang="ts">
import { Context } from '@/service/appContext';
import DateLib from '@/service/dateHelpers';
import DayTypeLib, { DayType } from '@/service/dayType';
import { computed } from 'vue';

const formattedRecords = computed(() => {
    const today = DateLib.treatAsUTC(DayTypeLib.setToStart(new Date(), DayType.Day));
    return Context.value.calc.rowsForDay(today).filter(x => x.from.getTime() === today.getTime());
});
</script>

<template>
    <div v-if="formattedRecords.length > 0">
        <p>Records that start today:</p>
        <div v-for="record in formattedRecords" v-bind:key="record.id">
            - {{ record.category }} <code>${{ record.amount.toFixed(2) }}</code> for <code> {{ Math.abs(record.calcPerDay()).toFixed(2) }}</code>/d
        </div>
    </div>
</template>
